#!/usr/bin/env python3
"""
Master Orchestration Layer
Coordinates NeuroForge, OpenClaw, Florra, and Opus
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

# Make sibling modules importable whether running from a repo checkout
# or from the Docker image (where the app lives at /app).
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

# Import all loggers
from airtable_sync import AirtableSync
from openclaw_airtable_logger import OpenClawAirtableLogger
from florra_airtable_logger import FlorraAirtableLogger
from opus_airtable_logger import OpusAirtableLogger


class MasterOrchestrator:
    def __init__(self):
        self.base_id = os.getenv("AIRTABLE_BASE_ID", "applXEAjh6k3Xmybl")
        self.api_key = os.getenv("AIRTABLE_API_KEY")
        self.output_dir = Path(os.getenv("NEUROFORGE_OUTPUT_DIR", PROJECT_DIR / "output"))
        
        # Initialize all loggers
        self.airtable_sync = AirtableSync(self.api_key, self.base_id)
        self.openclaw = OpenClawAirtableLogger()
        self.florra = FlorraAirtableLogger()
        self.opus = OpusAirtableLogger()
        
        self.config = self._load_config()
        
    def _load_config(self):
        """Load Airtable configuration"""
        config_path = Path(os.getenv("NEUROFORGE_CONFIG_DIR", PROJECT_DIR)) / "airtable-config.json"
        if config_path.exists():
            with open(config_path) as f:
                return json.load(f)
        return {}

    def log(self, message: str, prefix: str = "ℹ️"):
        timestamp = datetime.now().strftime("%H:%M:%S")
        print(f"{prefix} [{timestamp}] {message}")

    # ==========================================
    # NEUROFORGE → FLORRA Integration
    # ==========================================
    def sync_neuroforge_to_florra(self, topic: str):
        """Feed NeuroForge content into Florra campaigns"""
        self.log(f"Syncing NeuroForge '{topic}' to Florra campaigns...", "🔄")
        
        # Get NeuroForge project data
        output_dir = self.output_dir / topic.lower().replace(" ", "_")
        
        if not output_dir.exists():
            self.log(f"No output found for {topic}", "⚠️")
            return False
        
        # Extract generated content
        research_file = list(output_dir.glob("01_research_brief*.md"))
        scripts_file = list(output_dir.glob("04_shorts_scripts*.md"))
        
        if research_file and scripts_file:
            self.log(f"Found {len(research_file)} research files, {len(scripts_file)} script files", "📊")
            
            # Create campaign in Florra
            self.florra.add_to_ugc_pipeline(
                creator="NeuroForge Bot",
                campaign=topic,
                sound=f"{topic} Content",
                sound_id=f"neuroforge_{topic.lower().replace(' ', '_')}",
                status="Identified",
                notes=f"Auto-generated by NeuroForge on {datetime.now().isoformat()}"
            )
            
            self.log(f"Added '{topic}' to Florra UGC Pipeline", "✓")
            return True
        
        return False

    # ==========================================
    # FLORRA → OPUS Integration
    # ==========================================
    def sync_florra_content_to_opus(self, creator: str, platform: str = "TikTok"):
        """Schedule Florra content via Opus"""
        self.log(f"Scheduling {creator} content to {platform} via Opus...", "🔄")
        
        # Get content from Florra Content Library
        content = self.florra.get_content_by_creator(creator)
        
        if content:
            for item in content:
                clip_id = item.get("id")
                fields = item.get("fields", {})
                
                # Schedule in Opus
                self.opus.schedule_clip(
                    clip=fields.get("Filename", ""),
                    platform=platform,
                    scheduled_date=datetime.now().isoformat().split("T")[0],
                    caption=f"Check out @{creator} 🎬",
                    campaign=fields.get("Campaign Tags", "")
                )
            
            self.log(f"Scheduled {len(content)} clips from {creator}", "✓")
            return True
        
        return False

    # ==========================================
    # OPUS → OPENCLAW Learning
    # ==========================================
    def feed_opus_performance_to_openclaw(self):
        """Teach OpenClaw about top-performing clips"""
        self.log("Feeding Opus performance data to OpenClaw for learning...", "🔄")
        
        # Get scheduled clips from Opus
        scheduled = self.opus.get_scheduled_clips()
        
        if scheduled:
            for clip in scheduled:
                fields = clip.get("fields", {})
                caption = fields.get("Caption", "")
                platform = fields.get("Platform", "")
                
                # Log as interaction for OpenClaw to learn
                self.openclaw.log_interaction(
                    user_query=f"Clip caption analysis for {platform}",
                    response=f"Caption: {caption}",
                    search_used="Opus Performance",
                    satisfaction="Pending",
                    tags=f"opus,{platform.lower()},content"
                )
            
            self.log(f"Logged {len(scheduled)} clips to OpenClaw for analysis", "✓")
            return True
        
        return False

    # ==========================================
    # OPENCLAW → All Systems Optimization
    # ==========================================
    def get_openclaw_suggestions(self) -> list:
        """Get improvement suggestions from OpenClaw"""
        self.log("Fetching OpenClaw improvement suggestions...", "🔄")
        
        suggestions = self.openclaw.get_pending_improvements()
        
        if suggestions:
            self.log(f"Found {len(suggestions)} pending improvements", "✓")
            return suggestions
        
        self.log("No pending improvements", "⚠️")
        return []

    # ==========================================
    # Master Sync - All Systems
    # ==========================================
    def master_sync(self, topic: str = None, dry_run: bool = False):
        """Execute full system sync"""
        self.log("=" * 60, "📡")
        self.log("MASTER ORCHESTRATION SYNC", "📡")
        self.log("=" * 60, "📡")
        
        if dry_run:
            self.log("DRY-RUN MODE - No changes will be written", "🔍")
        
        print()
        
        # 1. NeuroForge sync
        self.log("Step 1: Syncing NeuroForge to Airtable...", "1️⃣")
        self.airtable_sync.sync_projects(topic=topic)
        self.airtable_sync.sync_pipeline_runs(topic=topic)
        
        print()
        
        # 2. NeuroForge → Florra
        if topic:
            self.log("Step 2: Syncing NeuroForge to Florra...", "2️⃣")
            self.sync_neuroforge_to_florra(topic)
        
        print()
        
        # 3. OpenClaw feedback
        self.log("Step 3: Feeding Opus performance to OpenClaw...", "3️⃣")
        self.feed_opus_performance_to_openclaw()
        
        print()
        
        # 4. Get improvements
        self.log("Step 4: Getting OpenClaw suggestions...", "4️⃣")
        suggestions = self.get_openclaw_suggestions()
        if suggestions:
            for i, s in enumerate(suggestions[:3], 1):
                issue = s.get("fields", {}).get("Issue", "Unknown")
                self.log(f"  {i}. {issue[:50]}...", "💡")
        
        print()
        self.log("=" * 60, "✓")
        self.log("MASTER SYNC COMPLETE", "✓")
        self.log("=" * 60, "✓")


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Master Orchestration Layer")
    parser.add_argument("--topic", type=str, help="Topic to sync")
    parser.add_argument("--dry-run", action="store_true", help="Preview only")
    
    args = parser.parse_args()
    
    orchestrator = MasterOrchestrator()
    orchestrator.master_sync(topic=args.topic, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
