#!/usr/bin/env python3
"""
NeuroForge OS — TokPortal Distributor
=======================================
Creates and configures a TokPortal bundle for geo-targeted TikTok/Instagram
distribution via real devices and local managers.

Flow:
  1. Read captions from scripts_parsed/script_NN.json
  2. Read video URLs from heygen_video_urls.json (or --video-urls-file)
  3. POST /bundles-create  → get bundle_id
  4. POST /account-configure (for account_and_videos bundles)
  5. POST /video-configure-at-position  × N scripts
  6. (optional) POST /bundles-publish

Prerequisites:
    export TOKPORTAL_API_KEY="tok_live_your_key_here"

Usage:
    # New account + 20 videos (TikTok, USA)
    python tokportal_distributor.py \\
        --topic "Clear Brain Fog" \\
        --faculty "Dr. Orion Hale" \\
        --country USA

    # Post on an existing saved account
    python tokportal_distributor.py \\
        --topic "Clear Brain Fog" \\
        --account-id acc_xxxxxxxxxxxx \\
        --country USA

    # Specify a custom video-URLs file (JSON: {"1": "https://...", "2": "https://..."})
    python tokportal_distributor.py \\
        --topic "Clear Brain Fog" \\
        --faculty "Dr. Orion Hale" \\
        --video-urls-file /path/to/my_video_urls.json

    # Dry run — print payloads without calling TokPortal
    python tokportal_distributor.py --topic "Clear Brain Fog" --faculty "Dr. Orion Hale" --dry-run

    # Auto-publish after configuration
    python tokportal_distributor.py --topic "Clear Brain Fog" --faculty "Dr. Orion Hale" --publish

Notes:
  - heygen_video_urls.json is generated by heygen_producer.py and contains
    temporary HeyGen CDN URLs. These may expire in 24–72 hours.
    For stable posting, upload your MP4s to Google Drive (public share link)
    or S3 and provide a --video-urls-file with the permanent URLs.
  - TokPortal requires target_start >= today + 3 days.
    Videos are scheduled daily starting from that date.
  - Verify endpoint paths at: https://developers.tokportal.com/bundles
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import date, timedelta
from pathlib import Path

import requests

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
OUTPUT_DIR = PROJECT_DIR / "output"

TOKPORTAL_BASE = "https://app.tokportal.com/api/ext"

# Allowed video quantities for account_and_videos bundles
ALLOWED_QUANTITIES = [5, 10, 25, 50, 100, 500]

SUPPORTED_COUNTRIES = ["USA", "UK", "FR", "CA", "IT", "PH"]


# ─────────────────────────────────────────────────────────────────────────────
# Auth
# ─────────────────────────────────────────────────────────────────────────────

def _headers() -> dict:
    key = os.environ.get("TOKPORTAL_API_KEY")
    if not key:
        print("Error: TOKPORTAL_API_KEY environment variable not set.")
        print("  Get your key from https://developers.tokportal.com")
        sys.exit(1)
    return {"X-API-Key": key, "Content-Type": "application/json"}


# ─────────────────────────────────────────────────────────────────────────────
# API calls
# ─────────────────────────────────────────────────────────────────────────────

def _post(endpoint: str, payload: dict, dry_run: bool, label: str) -> dict:
    """POST to a TokPortal endpoint. Returns parsed JSON or a dry-run stub."""
    if dry_run:
        print(f"  [DRY RUN] POST {endpoint}")
        print(f"  Payload: {json.dumps(payload, indent=4)}")
        return {"bundle_id": "dry_bundle_id", "status": "draft"}

    resp = requests.post(
        f"{TOKPORTAL_BASE}/{endpoint}",
        headers=_headers(),
        json=payload,
        timeout=30,
    )
    if not resp.ok:
        print(f"  ✗ {label} failed ({resp.status_code}): {resp.text}")
        sys.exit(1)
    return resp.json()


def create_bundle(bundle_type: str, platform: str, country: str,
                  videos_quantity: int, account_id: str,
                  niche: str, dry_run: bool) -> str:
    """Create a TokPortal bundle. Returns bundle_id."""
    payload = {
        "bundle_type": bundle_type,
        "platform":    platform,
        "country":     country,
    }
    if bundle_type in ("account_and_videos", "videos_only"):
        payload["videos_quantity"] = videos_quantity
    if bundle_type == "videos_only" and account_id:
        payload["existing_account_id"] = account_id
    if niche:
        payload["niche_warming"] = niche

    endpoint = "bundles-create-videos-only" if bundle_type == "videos_only" else "bundles-create"
    result = _post(endpoint, payload, dry_run, "Create bundle")

    bundle_id = result.get("bundle_id", "dry_bundle_id")
    print(f"  ✓ Bundle created: {bundle_id}  (type={bundle_type}, qty={videos_quantity})")
    return bundle_id


def configure_account(bundle_id: str, username_hint: str,
                      profile_pic_url: str, dry_run: bool):
    """Configure the account for an account_and_videos bundle."""
    payload = {"bundle_id": bundle_id}
    if username_hint:
        payload["desired_username"] = username_hint
    if profile_pic_url:
        payload["profile_picture_url"] = profile_pic_url

    _post("account-configure", payload, dry_run, "Configure account")
    print(f"  ✓ Account configured")


def configure_video(bundle_id: str, position: int, caption: str,
                    video_url: str, target_start: str, dry_run: bool):
    """Configure a single video slot at the given 1-indexed position."""
    payload = {
        "bundle_id":    bundle_id,
        "position":     position,
        "caption":      caption,
        "video_url":    video_url,
        "target_start": target_start,
    }
    _post("video-configure-at-position", payload, dry_run,
          f"Configure video position {position}")
    print(f"  ✓ Position {position:02d}  target_start={target_start}  "
          f"caption={caption[:60]}{'...' if len(caption) > 60 else ''}")


def publish_bundle(bundle_id: str, dry_run: bool):
    """Publish the bundle (wallet is charged at this point)."""
    payload = {"bundle_id": bundle_id}
    _post("bundles-publish", payload, dry_run, "Publish bundle")
    print(f"  ✓ Bundle published: {bundle_id}")


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _snap_quantity(n: int) -> int:
    """Round n up to the nearest allowed TokPortal video quantity."""
    for q in ALLOWED_QUANTITIES:
        if q >= n:
            return q
    return ALLOWED_QUANTITIES[-1]


def _build_caption(script: dict) -> str:
    """Build a TikTok caption from parsed script JSON. Max 2,200 chars."""
    if script.get("tiktok_caption"):
        return script["tiktok_caption"][:2200]
    parts = []
    if script.get("caption_hook"):
        parts.append(script["caption_hook"])
    if script.get("hashtags"):
        parts.append(script["hashtags"])
    return ("\n\n".join(parts) or script.get("hook", ""))[:2200]


def _schedule_dates(n: int, start_offset_days: int = 3) -> list[str]:
    """Return n ISO date strings spaced 1 day apart, starting today + offset."""
    base = date.today() + timedelta(days=start_offset_days)
    return [(base + timedelta(days=i)).isoformat() for i in range(n)]


def parse_range(s: str) -> list[int]:
    nums = set()
    for part in s.split(","):
        part = part.strip()
        if "-" in part:
            a, b = part.split("-", 1)
            nums.update(range(int(a), int(b) + 1))
        else:
            nums.add(int(part))
    return sorted(nums)


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Submit a NeuroForge topic to TokPortal for distribution"
    )
    parser.add_argument("--topic",    required=True,
                        help='Topic name e.g. "Clear Brain Fog"')
    parser.add_argument("--faculty",  default="",
                        help="Faculty name (used for account username hint)")
    parser.add_argument("--platform", default="tiktok",
                        choices=["tiktok", "instagram"],
                        help="Target platform (default: tiktok)")
    parser.add_argument("--country",  default="USA",
                        choices=SUPPORTED_COUNTRIES,
                        help="Target country for account creation (default: USA)")
    parser.add_argument("--account-id", default="",
                        dest="account_id",
                        help="Existing TokPortal account ID for videos_only bundles")
    parser.add_argument("--scripts",  default="",
                        help="Script numbers to include, e.g. '1-20' or '1,3,5' (default: all)")
    parser.add_argument("--start-offset", type=int, default=3,
                        dest="start_offset",
                        help="Days from today for first post (min 3, default 3)")
    parser.add_argument("--video-urls-file", default="",
                        dest="video_urls_file",
                        help="JSON file mapping script number to video URL. "
                             "Defaults to output/{topic}/heygen_video_urls.json")
    parser.add_argument("--niche",    default="",
                        help="Niche for account warming e.g. 'neuroscience, brain health'")
    parser.add_argument("--publish",  action="store_true",
                        help="Publish bundle after configuration (wallet charged)")
    parser.add_argument("--dry-run",  action="store_true",
                        help="Print payloads without calling TokPortal API")
    args = parser.parse_args()

    safe_topic = re.sub(r"[^a-zA-Z0-9_]", "_", args.topic.lower())
    topic_dir  = OUTPUT_DIR / safe_topic

    # ── Load parsed script JSONs ──────────────────────────────────────────
    scripts_dir = topic_dir / "scripts_parsed"
    if not scripts_dir.exists():
        print(f"Error: No parsed scripts at {scripts_dir}")
        print("  Run parse_scripts.py first.")
        sys.exit(1)

    script_files = sorted(scripts_dir.glob("script_*.json"))
    if not script_files:
        print(f"Error: No script_*.json files in {scripts_dir}")
        sys.exit(1)

    if args.scripts:
        wanted = set(parse_range(args.scripts))
        script_files = [f for f in script_files
                        if int(re.search(r"(\d+)", f.stem).group(1)) in wanted]

    scripts = [json.loads(f.read_text(encoding="utf-8")) for f in script_files]
    n = len(scripts)

    # ── Load video URLs ───────────────────────────────────────────────────
    urls_file = Path(args.video_urls_file) if args.video_urls_file else \
                topic_dir / "heygen_video_urls.json"

    if not urls_file.exists():
        print(f"Error: No video URLs file found at {urls_file}")
        print("  Options:")
        print("    1. Run heygen_producer.py to generate videos (URLs saved automatically)")
        print("    2. Provide --video-urls-file with a JSON map: {\"1\": \"https://...\", ...}")
        sys.exit(1)

    video_urls: dict = json.loads(urls_file.read_text(encoding="utf-8"))
    # Normalise keys to int
    video_urls = {int(k): v for k, v in video_urls.items()}

    # Check coverage
    missing_urls = [s["number"] for s in scripts if s["number"] not in video_urls]
    if missing_urls:
        print(f"Warning: No video URL for script(s): {missing_urls}")
        print("  These positions will be skipped during configuration.")

    configurable = [s for s in scripts if s["number"] in video_urls]
    if not configurable:
        print("Error: No scripts have matching video URLs. Nothing to do.")
        sys.exit(1)

    # ── Determine bundle type ─────────────────────────────────────────────
    bundle_type    = "videos_only" if args.account_id else "account_and_videos"
    videos_quantity = _snap_quantity(len(configurable))
    start_offset   = max(args.start_offset, 3)
    schedule       = _schedule_dates(len(configurable), start_offset)

    print(f"\n{'='*60}")
    print(f"  TOKPORTAL DISTRIBUTOR")
    print(f"  Topic:    {args.topic}")
    if args.faculty:
        print(f"  Faculty:  {args.faculty}")
    print(f"  Platform: {args.platform.upper()}")
    print(f"  Country:  {args.country}")
    print(f"  Type:     {bundle_type}")
    print(f"  Videos:   {len(configurable)} (bundle slots: {videos_quantity})")
    print(f"  Schedule: {schedule[0]} → {schedule[-1]}")
    print(f"  Publish:  {'YES — wallet will be charged' if args.publish else 'No (draft)'}")
    print(f"  Mode:     {'DRY RUN' if args.dry_run else 'LIVE'}")
    print(f"{'='*60}\n")

    # ── Step 1: Create bundle ─────────────────────────────────────────────
    bundle_id = create_bundle(
        bundle_type=bundle_type,
        platform=args.platform,
        country=args.country,
        videos_quantity=videos_quantity,
        account_id=args.account_id,
        niche=args.niche,
        dry_run=args.dry_run,
    )

    # ── Step 2: Configure account (account_and_videos only) ───────────────
    if bundle_type == "account_and_videos":
        # Derive a username hint from the faculty name e.g. "dr.orion.hale"
        username_hint = re.sub(r"[^a-z0-9]", ".", args.faculty.lower()).strip(".") \
                        if args.faculty else ""
        configure_account(bundle_id, username_hint, profile_pic_url="", dry_run=args.dry_run)

    # ── Step 3: Configure each video slot ────────────────────────────────
    print(f"\n[ Configuring {len(configurable)} video slots ]\n")
    for position, (script, target_start) in enumerate(zip(configurable, schedule), start=1):
        num = script["number"]
        caption   = _build_caption(script)
        video_url = video_urls[num]
        configure_video(bundle_id, position, caption, video_url,
                        target_start, args.dry_run)
        if not args.dry_run:
            time.sleep(0.5)  # brief pause between configure calls

    # ── Step 4: Publish (optional) ────────────────────────────────────────
    if args.publish:
        print(f"\n[ Publishing bundle ]")
        publish_bundle(bundle_id, args.dry_run)

    # ── Save bundle record ────────────────────────────────────────────────
    record = {
        "bundle_id":    bundle_id,
        "bundle_type":  bundle_type,
        "platform":     args.platform,
        "country":      args.country,
        "scripts":      [s["number"] for s in configurable],
        "schedule":     schedule,
        "published":    args.publish,
        "dry_run":      args.dry_run,
    }
    log_path = topic_dir / "tokportal_bundle_log.json"
    existing = json.loads(log_path.read_text(encoding="utf-8")) if log_path.exists() else []
    existing.append(record)
    log_path.write_text(json.dumps(existing, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"\n{'='*60}")
    print(f"  BUNDLE {'PUBLISHED' if args.publish else 'CONFIGURED (draft)'}")
    print(f"  Bundle ID:  {bundle_id}")
    print(f"  Videos:     {len(configurable)} configured")
    print(f"  Log:        {log_path.name}")
    if not args.publish:
        print(f"\n  To publish, run:")
        print(f"    python tokportal_distributor.py --topic \"{args.topic}\" --publish")
        print(f"  Or publish manually at: https://app.tokportal.com")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
