#!/usr/bin/env python3
"""
Florra OS — Clip Engine
=======================
The behind-the-scenes clipping machine for Florra's marketing firepower.

Turns podcast/source audio into platform-ready short clips and schedules them
to TikTok / Instagram / YouTube. It is the Opus layer of Florra OS: it reads
which podcasts are marked for auto-clipping, generates clips, logs every clip
to the Opus Airtable tables, and hands finished MP4s to the Postiz integration
for scheduling.

Flow:
    Podcast (auto-clip enabled)
      → clip generated (or imported from Opus / a local videos dir)
      → logged to Airtable (Opus Clips)
      → scheduled via Postiz (TikTok / IG / YouTube)
      → performance logged back to Airtable

Usage:
    python clip_engine.py --mode ingest --source "https://.../episode.mp3"
    python clip_engine.py --mode schedule --topic "Podcast Name" --dry-run
    python clip_engine.py --mode schedule --topic "Podcast Name" --start-date 2026-09-07

Env (see ../neuroforge-os/.env.example):
    AIRTABLE_API_KEY / AIRTABLE_BASE_ID  — Opus logger
    POSTIZ_API_KEY / POSTIZ_BASE_URL     — posting layer
    POSTIZ_INTEGRATION_IDS               — optional platform->id JSON
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import requests

# ── Paths ──────────────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).resolve().parent
CLIP_DIR = SCRIPT_DIR / "clips"          # finished MP4s land here
MANIFEST = SCRIPT_DIR / "manifest.json"  # local log of generated/scheduled clips

# Allow running from anywhere; the Opus logger lives in neuroforge-os/scripts.
NEUROFORGE_SCRIPTS = Path(os.getenv(
    "NEUROFORGE_SCRIPTS_DIR",
    SCRIPT_DIR.parent / "neuroforge-os" / "scripts",
))

# ── Platform config (mirrors postiz_integration.py) ────────────────────────

VIDEO_DAYS = [0, 2, 4]  # Mon / Wed / Fri
PLATFORM_SETTINGS = {
    "tiktok": {
        "__type": "tiktok",
        "privacy_level": "PUBLIC_TO_EVERYONE",
        "duet": True,
        "stitch": True,
        "comment": True,
        "autoAddMusic": "no",
        "brand_content_toggle": False,
        "brand_organic_toggle": False,
        "video_made_with_ai": True,
        "content_posting_method": "DIRECT_POST",
    },
    "instagram": {"__type": "instagram", "post_type": "post", "is_trial_reel": False, "collaborators": []},
    "youtube": {"__type": "youtube", "type": "public", "selfDeclaredMadeForKids": "no"},
}


def _env(key: str, default: str = "") -> str:
    return os.environ.get(key, default)


# ── Airtable (Opus logger) ─────────────────────────────────────────────────

class OpusAirtable:
    """Thin wrapper over the Opus Airtable tables (mirrors opus_airtable_logger)."""

    def __init__(self):
        self.api_key = _env("AIRTABLE_API_KEY")
        self.base_id = _env("AIRTABLE_BASE_ID", "applXEAjh6k3Xmybl")
        self.api_base = "https://api.airtable.com/v0"
        self.tables = {
            "projects": "tblvMbbfjYrOuPqwS",
            "clips": "tblW3n5Fjr9lBgJph",
            "scheduling": "tblKYGRy5jU89q66Z",
            "podcasts": "tblT4R7RtjEpDcwi3",
            "performance": "tblSOYD7BfyIY77e6",
        }
        self.headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

    def auto_clip_podcasts(self) -> list:
        """Podcasts with Auto Clip Enabled = Yes."""
        if not self.api_key:
            return []
        resp = requests.get(
            f"{self.api_base}/{self.base_id}/{self.tables['podcasts']}"
            f"?filterByFormula={{Auto Clip Enabled}}='Yes'",
            headers=self.headers, timeout=30,
        )
        return resp.json().get("records", []) if resp.status_code == 200 else []

    def log_clip(self, project: str, clip_number: int, title: str,
                 video_url: str = "", download_path: str = "") -> str:
        record = {
            "fields": {
                "Project": project,
                "Clip Title": title,
                "Video URL": video_url,
                "Download Path": download_path,
                "Engagement Predicted": "Pending",
                "Platform Ready": "Yes",
                "Notes": f"Clip {clip_number} generated by Clip Engine",
            }
        }
        resp = requests.post(
            f"{self.api_base}/{self.base_id}/{self.tables['clips']}",
            headers=self.headers, json=record, timeout=30,
        )
        if resp.status_code in (200, 201):
            return resp.json().get("id", "")
        print(f"  ⚠️  Failed to log clip: {resp.text[:200]}", file=sys.stderr)
        return ""


# ── Postiz (posting layer) ─────────────────────────────────────────────────

class Postiz:
    """Minimal Postiz client — upload + schedule, matching postiz_integration.py."""

    def __init__(self, base_url: str, api_key: str, dry_run: bool = False):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.dry_run = dry_run
        self.headers = {"Authorization": api_key}

    def resolve_ids(self, platforms: list) -> dict:
        override = _env("POSTIZ_INTEGRATION_IDS")
        if override:
            try:
                return json.loads(override)
            except json.JSONDecodeError:
                print("  ⚠️  POSTIZ_INTEGRATION_IDS invalid JSON", file=sys.stderr)
        if self.dry_run:
            return {p: f"dry-{p}" for p in platforms}
        resp = requests.get(f"{self.base_url}/integrations", headers=self.headers, timeout=30)
        resp.raise_for_status()
        out = {}
        for p in platforms:
            matches = [i for i in resp.json()
                       if i.get("identifier") == p and not i.get("disabled")]
            if matches:
                out[p] = matches[0]["id"]
        return out

    def upload(self, filepath: Path) -> dict:
        if self.dry_run:
            return {"id": f"dry-{filepath.stem}", "path": f"file://{filepath.name}"}
        with open(filepath, "rb") as f:
            resp = requests.post(
                f"{self.base_url}/upload", headers=self.headers,
                files={"file": (filepath.name, f, "video/mp4")}, timeout=300,
            )
        resp.raise_for_status()
        return resp.json()

    def schedule(self, platform: str, integration_id: str, content: str,
                 media: list, title: str, publish_at: datetime) -> str:
        settings = dict(PLATFORM_SETTINGS[platform])
        if platform == "youtube":
            settings["title"] = title[:100]
        elif platform == "tiktok":
            settings["title"] = title[:90]

        payload = {
            "type": "schedule",
            "date": publish_at.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
            "shortLink": False,
            "tags": [],
            "posts": [{
                "integration": {"id": integration_id},
                "value": [{"content": content, "image": media}],
                "settings": settings,
            }],
        }
        if self.dry_run:
            return "dry-run"
        resp = requests.post(f"{self.base_url}/posts", headers=self.headers,
                             json=payload, timeout=30)
        resp.raise_for_status()
        created = resp.json()
        return created[0].get("postId", "unknown") if isinstance(created, list) else created


# ── Clip Engine core ───────────────────────────────────────────────────────

def load_manifest() -> list:
    if MANIFEST.exists():
        return json.loads(MANIFEST.read_text(encoding="utf-8"))
    return []


def save_manifest(records: list) -> None:
    MANIFEST.write_text(json.dumps(records, indent=2), encoding="utf-8")


def ingest_clip(source: str, title: str = "", project: str = "Podcast") -> Path:
    """Import a clip (download or copy) into the engine's clips/ dir."""
    CLIP_DIR.mkdir(parents=True, exist_ok=True)
    name = re.sub(r"[^a-zA-Z0-9_-]", "_", title or Path(source).stem)
    dest = CLIP_DIR / f"{name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.mp4"

    if source.startswith("http"):
        print(f"  ↓ Downloading {source}")
        resp = requests.get(source, timeout=300, stream=True)
        resp.raise_for_status()
        with open(dest, "wb") as f:
            for chunk in resp.iter_content(chunk_size=1 << 16):
                f.write(chunk)
    else:
        src = Path(source)
        if not src.exists():
            print(f"Error: {source} does not exist", file=sys.stderr)
            sys.exit(1)
        dest.write_bytes(src.read_bytes())

    print(f"  ✓ Ingested: {dest}")
    return dest


def schedule_clips(clips: list, platforms: list, start_date: datetime,
                   interval_days: int, dry_run: bool) -> dict:
    """Schedule a list of (filepath, caption, title) tuples via Postiz."""
    api_key = _env("POSTIZ_API_KEY")
    if not api_key and not dry_run:
        print("Error: POSTIZ_API_KEY not set.", file=sys.stderr)
        sys.exit(1)

    postiz = Postiz(_env("POSTIZ_BASE_URL", "https://api.postiz.com/public/v1"),
                    api_key, dry_run=dry_run)
    ids = postiz.resolve_ids(platforms)
    if not ids:
        print("Error: no integrations resolved.", file=sys.stderr)
        sys.exit(1)

    results = {"scheduled": 0, "failed": 0}
    publish_at = start_date
    while publish_at.weekday() not in VIDEO_DAYS:
        publish_at += timedelta(days=1)

    for clip in clips:
        filepath, caption, title = clip
        if not filepath.exists():
            print(f"  ✗ Missing {filepath}", file=sys.stderr)
            results["failed"] += 1
            continue
        try:
            media = [postiz.upload(filepath)]
        except requests.RequestException as e:
            print(f"  ✗ Upload failed for {filepath.name}: {e}", file=sys.stderr)
            results["failed"] += 1
            continue

        for platform in platforms:
            if platform not in ids:
                continue
            try:
                postiz.schedule(platform, ids[platform], caption, media, title, publish_at)
                print(f"  ✓ {platform} -> {publish_at.date()} ({filepath.name})")
                results["scheduled"] += 1
            except requests.RequestException as e:
                print(f"  ✗ {platform} failed: {e}", file=sys.stderr)
                results["failed"] += 1
        publish_at += timedelta(days=interval_days)

    return results


# ── CLI ────────────────────────────────────────────────────────────────────

def cmd_ingest(args):
    dest = ingest_clip(args.source, args.title, args.project)
    record = {
        "file": str(dest),
        "project": args.project,
        "title": args.title or dest.stem,
        "ingested": datetime.now(timezone.utc).isoformat(),
        "scheduled": False,
    }
    manifest = load_manifest()
    manifest.append(record)
    save_manifest(manifest)
    print(f"\n✓ Ingested clip logged to manifest ({len(manifest)} total)")


def cmd_schedule(args):
    manifest = load_manifest()
    if not manifest:
        print("No clips in manifest. Run --mode ingest first (or place MP4s in clips/).",
              file=sys.stderr)
        sys.exit(1)

    # Ready clips = ingested and not yet scheduled
    clips = []
    for rec in manifest:
        if rec.get("scheduled"):
            continue
        filepath = Path(rec["file"])
        caption = rec.get("title", "")
        if caption:
            caption += "\n\n#podcastclips #florra"
        clips.append((filepath, caption, rec.get("title", "Clip")))

    if not clips:
        print("All clips already scheduled.")
        return

    platforms = [p.strip() for p in args.platforms.split(",") if p.strip()]
    start = datetime.now(timezone.utc).replace(tzinfo=None) + timedelta(days=1)
    if args.start_date:
        start = datetime.strptime(args.start_date, "%Y-%m-%d")

    print(f"\n{'='*60}")
    print(f"  CLIP ENGINE — SCHEDULE")
    print(f"  Clips:     {len(clips)}")
    print(f"  Platforms: {', '.join(platforms)}")
    print(f"  Mode:      {'DRY RUN' if args.dry_run else 'LIVE'}")
    print(f"{'='*60}\n")

    results = schedule_clips(clips, platforms, start, args.interval_days, args.dry_run)

    # Mark scheduled in manifest (only on live run)
    if not args.dry_run:
        for rec in manifest:
            if not rec.get("scheduled"):
                rec["scheduled"] = True
                rec["scheduled_at"] = datetime.now(timezone.utc).isoformat()
        save_manifest(manifest)

    print(f"\n✓ SCHEDULED: {results['scheduled']}  FAILED: {results['failed']}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Florra OS Clip Engine — generate/schedule short clips"
    )
    parser.add_argument("--mode", choices=["ingest", "schedule"], required=True,
                        help="ingest: add a clip; schedule: push clips to Postiz")
    parser.add_argument("--source", default="", help="Clip source URL or local path (ingest)")
    parser.add_argument("--title", default="", help="Clip title/caption (ingest)")
    parser.add_argument("--project", default="Podcast", help="Project name (ingest)")
    parser.add_argument("--platforms", default="tiktok,instagram,youtube")
    parser.add_argument("--start-date", default=None, help="First publish date YYYY-MM-DD")
    parser.add_argument("--interval-days", type=int, default=2)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()
    if args.mode == "ingest":
        cmd_ingest(args)
    else:
        cmd_schedule(args)


if __name__ == "__main__":
    main()
